### PR TITLE
environments directory configuration

### PR DESCRIPTION
**Pull request by jmervine**
I've added a feature to allow for creating an "environments" directory within the yacht root directory. Files contained with in are loaded, using the file name as the root key. See load.feature and my updates to README.rdoc for an example.

### CODE REVIEW

**Comment by bowsersenior** [comment]
Thanks for this pull request! I think this is a good idea in general, but the devil is in the details:
- I'm concerned about having `base.yml`, `local.yml` as well as the `environments` directory. I think it's better to have a single `environments` directory which loads everything. Perhaps `base.yml` and `local.yml` can be loaded from there?
- Load order issues may arise if there an env from one file is inherited in another file. Perhaps we could resolve this by using file names instead of environment names for inheritance?

All in all, I'd say this is a good start, but we need to figure out some solutions to the issues above to make Yacht simpler with this update, instead of more complex. I'll try to work on some possible solutions and get back to you.

Thanks again!

-Mani

**Comment by ricokareem** [comment]
@bowsersenior @jmervine :+1: miss you fools!

**Comment by bowsersenior** [comment]
@ricokareem :)

**Comment by jmervine** [comment]
@ricokareem :P

**Pull request closed without merging**
